### ISSUE TITLE
Claw mode should change my sabers to claws

### ISSUE THREAD

**Issue by bbarhight** [SteffanDonal/BeatSaber-Claws#1]
Currently, when I desire to play in Claw Mode, I need to get out of the song select window and go to the saber select window. I'd like this plugin to handle the saber swap for me.

#Scenarios 

Given: 
I have a custom saber selected
When: 
I activate claw mode
Then: 
My chosen saber is now the `Claws.saber` file.

Given:
I have claw mode activated
And: 
Claw mode has changed my custom saber from `another.saber`, 
When: 
I uncheck claw mode
then:
My chosen saber is now `another.saber`.

**Comment by bbarhight** [comment]
Totally should have forked this before I started making issues. Oh well.

**Comment by bbarhight** [comment]
see #8

**Comment by SteffanDonal** [comment]
Thank you 💗
