### ISSUE TITLE
Beat Saber's own adjustments are applied to Claws

### ISSUE THREAD

**Issue by SteffanDonal** [SteffanDonal/BeatSaber-Claws#10]
Claws positioning should be consistent between all setups; custom positioning for Claws is a separate feature, so this is a bug.

**Comment by AeliusSaionji** [comment]
Hey!
I just attempted to use this mod with a vive tracker, and although beatsaber has the saber pointed the right way, claws assume a perpendicular orientation.

Beatsaber used to do this to me. For whatever reason, beatsaber applies the correct orientation but claws mod does not.

This may be a related issue?

**Comment by SteffanDonal** [comment]
Hmm. Strictly it's related, but here I think it might actually be desirable for you - without Beat Saber's own adjustments, it's currently not possible to create your own custom calibration for claws...

I wouldn't be able to make a "universal Vive tracker" calibration, so I think maybe a separate issue needs to be made for this. There should be a way to create/adjust claws calibrations!

Are you finding it's impossible to adjust at all ATM?

**Comment by SteffanDonal** [comment]
@AeliusSaionji If you still need this fixed, please raise a new issue. This one's fixed!
