### ISSUE TITLE
Quest 2 Controllers

### ISSUE THREAD

**Issue by ljamesbarnes** [SteffanDonal/BeatSaber-Claws#16]
Received this error when attempting to use with Quest 2 and Controllers

[ERROR @ 20:09:26 | Claws] Discovering controller: OpenVR Controller(Oculus Quest2 (Left Controller)) - Left failed! Please open an issue with this log statement.
[ERROR @ 20:09:26 | Claws] Discovering controller: OpenVR Controller(Oculus Quest2 (Right Controller)) - Right failed! Please open an issue with this log statement.

**Comment by SteffanDonal** [comment]
Thanks for the issue and log - it's ultra helpful.
I'm going to be fixing this for both Quest over Link and Quest over Virtual Desktop today!

My notes:
Virtual Desktop: OpenVR Controller(Miramar (Left Controller))
Link: OpenVR Controller(Oculus Quest2 (Right Controller))
