### ISSUE TITLE
Saber trail length remains at claws size after claws is deselected (intermittent)

### ISSUE THREAD

**Issue by bbarhight** [SteffanDonal/BeatSaber-Claws#7]

**Comment by bbarhight** [comment]
this could be the cause of QTpop's "it feels like the fps is lower in the headset" problem.

**Comment by SteffanDonal** [comment]
Noticed this too - likely due to how XWeaponTrail works internally & Beat Saber now recycling objects instead of loading entirely new ones.

One approach here could be to remove & re-add the XWeaponTrail component, to force it to reinitialise properly.

**Comment by bbarhight** [comment]
> Beatsaber recycling objects instead of loading entirely new ones 

Well that's... one way to ignore/optimize for GC.  Would replacing the XWeapontTrail component eventually cause some memory issues? I'm less familiar w/ Unity than C#, and less familiar with C# than I should be.

**Comment by bbarhight** [comment]
Orrrr the rotation gets handled by a `HarmonyPatch` runtime injection/replacement, but the length isn't explicitly updated again after load.

**Comment by SteffanDonal** [comment]
If this trail issue is still a thing, replacing the component most likely won't cause any issues. I believe the built-in Unity methods for cloning GameObjects would be just fine for this

**Comment by SteffanDonal** [comment]
Tentative closing of this as I believe it's fixed!

Thank you 💗
